// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5933.Rosieppbs;

import org.usfirst.frc5933.Rosieppbs.commands.*;
import org.usfirst.frc5933.Rosieppbs.subsystems.*;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import java.util.Scanner;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {
	Command arcadeDrive;
	Command autonomousCommand;

	public static OI oi;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static DriveTrain driveTrain;
	public static PingPongBallCannon pingPongBallCannon;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	private Helmsman helmsman_;

	/**
	 * This function is run when the robot is first started up and should be
	 * used for any initialization code.
	 */
	public void robotInit() {
		RobotMap.init();
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		driveTrain = new DriveTrain();
		pingPongBallCannon = new PingPongBallCannon();

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		// OI must be constructed after subsystems. If the OI creates Commands
		//(which it very likely will), subsystems are not guaranteed to be
		// constructed yet. Thus, their requires() statements may grab null
		// pointers. Bad news. Don't move it.
		oi = new OI();

		// instantiate the command used for the autonomous period
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

		autonomousCommand = new AutonomousCommand();

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS


		arcadeDrive = new ArcadeDrive();
		helmsman_ = new Helmsman("10.59.33.21", 59330);  

		if (!helmsman_.connect()) {  
			System.err.println("Failed to connect to the Helmsman and I really need my mayonnaise");  
		}  else{
			System.out.println("Connected. No mayo for me.");
		}
	}

	/**
	 * This function is called when the disabled button is hit.
	 * You can use it to reset subsystems before shutting down.
	 */
	public void disabledInit(){

	}

	public void disabledPeriodic() {
		Scheduler.getInstance().run();
	}

	public void autonomousInit() {
		// schedule the autonomous command (example)
		if (autonomousCommand != null) autonomousCommand.start();
	}
	// TODO: Put in the correct ip and port  



	/**
	 * This function is called periodically during autonomous
	 */
	public void autonomousPeriodic() {
		Scheduler.getInstance().run();
	}

	public void teleopInit() {
		// This makes sure that the autonomous stops running when
		// teleop starts running. If you want the autonomous to
		// continue until interrupted by another command, remove
		// this line or comment it out.
		if (autonomousCommand != null) autonomousCommand.cancel();
	}
	public void take_directions_from_helmsman() {  
		if (!helmsman_.is_connected()) 
			return;  

		if (helmsman_.recv()){
			System.out.println("Recieved packet");
		}else{
			//System.out.println("No go");
		}
		String direction = helmsman_.get_direction();  
		double degrees = 0;  
		switch (direction)   
		{  
		case Helmsman.NADA:  
			return;  
		case Helmsman.LEFT:  
			degrees = helmsman_.get_degrees();  
			driveTrain.turn_left(degrees);  
		case Helmsman.RIGHT:  
			degrees = helmsman_.get_degrees();  
			driveTrain.turn_left(degrees);  
		}  
	}  


	/**
	 * This function is called periodically during operator control
	 */
	boolean notPressed = true;
	long startTime = 0;
	long spinUpTime = 1000;
	long pistonRunTime = 1620; //start at 1485
	double wheelSpeed = -.5;
	public void teleopPeriodic() {
		Scheduler.getInstance().run();
		/*if (oi.getJoystick1().getRawButton(1)){
			pingPongBallCannon.wheelSpeed(-.5);
		}
		if (!(oi.getJoystick1().getRawButton(1))){
			pingPongBallCannon.wheelSpeed(0);
		}*/
		
		if(oi.getJoystick1().getRawButton(1)){
			pingPongBallCannon.pistonStart();
		}if(!oi.getJoystick1().getRawButton(1)){
			pingPongBallCannon.pistonStop();
		}

		if(oi.getJoystick1().getRawButton(4)){
			wheelSpeed = -.58;
		}
		
		if(oi.getJoystick1().getRawButton(3)){
			wheelSpeed = -.35;
		}
		
		if(oi.getJoystick1().getRawButton(2)){
			wheelSpeed = -.4167;//mid speed
		}
		
		if (oi.getJoystick1().getRawButton(5)&&notPressed) {
			startTime = System.currentTimeMillis();
			pingPongBallCannon.wheelSpeed(wheelSpeed);
			notPressed = false;
		}if ((startTime <= (System.currentTimeMillis() - spinUpTime))&&!notPressed){
			pingPongBallCannon.pistonStart();
		}if ((startTime <= (System.currentTimeMillis() - (spinUpTime + pistonRunTime)))&&!notPressed) {//try this at 1485 first, change after testing.
			pingPongBallCannon.pistonStop();
		}if ((startTime <= (System.currentTimeMillis() - (spinUpTime + pistonRunTime + 500)))&&!notPressed&&!oi.getJoystick1().getRawButton(5)){
			notPressed = true;
			pingPongBallCannon.wheelSpeed(0);
			spinUpTime = 1000;
		}else if ((startTime <= (System.currentTimeMillis() - (spinUpTime + pistonRunTime + 500)))&&!notPressed&&oi.getJoystick1().getRawButton(5)){
			notPressed = true;
			spinUpTime = 0;
		}

		if (arcadeDrive != null){
			arcadeDrive.start();
		}

		take_directions_from_helmsman(); //use the above method
	}

	/**
	 * This function is called periodically during test mode
	 */
	public void testPeriodic() {
		LiveWindow.run();
	}
}
